apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-kafka
  name: udaconnect-kafka
spec:
  ports:
  - name: "5000"
    port: 5000
  selector:
    service: udaconnect-kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-kafka
  name: udaconnect-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-kafka
  template:
    metadata:
      labels:
        service: udaconnect-kafka
    spec:
      containers:
      - image: prabormukherjee/udaconnect-kafka:latest
        name: udaconnect-kafka
        imagePullPolicy: Always
      restartPolicy: Always
