---
swagger: '2.0'
basePath: "/"
paths:
  "/api/persons":
    get:
      responses:
        '200':
          description: Success
      operationId: get_persons_resource
      tags:
      - persons_api
    post:
      responses:
        '200':
          description: Success
      operationId: post_persons_resource
      tags:
      - persons_api
  "/api/persons/{person_id}":
    parameters:
    - in: path
      description: Unique ID for a given Person
      name: person_id
      required: true
      type: string
    get:
      responses:
        '200':
          description: Success
      operationId: get_person_resource
      tags:
      - persons_api
info:
  title: UdaConnect persons API
  version: 0.1.0
produces:
- application/json
consumes:
- application/json
tags:
- name: persons_api
  description: Connections via geolocation.
responses:
  ParseError:
    description: When a mask can't be parsed
  MaskError:
    description: When any error occurs on mask
